import { PrismaClient } from '@prisma/client';

export async function seedModels(prisma: PrismaClient) {
  const modelNames = [
    'BMW i3',
    'BMW X3',
    'BMW X5',
    'BMW X7',
    'BMW 3 Series',
    'BMW 5 Series',
    'BMW 7 Series',
    'Mercedes-Benz EQC',
    'Mercedes-Benz CLS',
    'Mercedes-Benz S-Class',
    'Audi A3',
    'Audi A4',
    'Audi A5',
    'Audi A6',
    'Audi A8',
    'Audi Q5',
    'Audi Q7',
    'Audi TT',
    'Tesla Model 3',
    'Tesla Model S',
    'Tesla Model X',
    'Toyota Corolla',
    'Toyota Camry',
    'Toyota RAV4',
    'Toyota Highlander',
    'Honda Civic',
    'Honda Accord',
    'Honda CR-V',
    'Honda Pilot',
    'Nissan Altima',
    'Nissan Maxima',
    'Nissan Rogue',
    'Kia Soul',
    'Kia Optima',
    'Kia Sorento',
    'Volkswagen Golf',
    'Volkswagen Jetta',
    'Volkswagen Passat',
    'Volkswagen Tiguan',
    'Volkswagen Arteon',
    'Ford Focus',
    'Ford Fusion',
    'Ford Mustang',
    'Ford Explorer',
    'Ford Edge',
    'General Motors Bolt',
    'General Motors Cruze',
    'General Motors Silverado',
    'General Motors Equinox',
    'Hyundai Elantra',
    'Hyundai Santa Fe',
    'Hyundai Tucson',
    'Hyundai Kona',
    'Peugeot 208',
    'Peugeot 308',
    'Peugeot 508',
    'Peugeot 5008',
    'Renault Clio',
    'Renault Megane',
    'Renault Captur',
    'Volvo XC90',
    'Volvo V60',
    'Volvo S90',
    'Fiat 500',
    'Fiat Panda',
    'Fiat Punto',
    'Fiat Panda',
    'Fiat Seicento',
    'Seat Leon',
    'Opel Astra',
    'Opel Corsa',
    'Opel Insignia',
    'Opel Mokka',
    'KTM 125',
    'KTM 250',
    'KTM 390',
    'Suzuki Jimny',
    'Suzuki Swift',
    'Suzuki Cappuccino',
    'Harley-Davidson Softail',
    'Harley-Davidson Electra Glide',
    'Kawasaki Ninja',
    'Kawasaki Ninja ZX-6R',
    'Kawasaki Z900',
  ];

  const createdModels = await prisma.models.createMany({
    data: modelNames.map((name) => ({ name })),
    skipDuplicates: true,
  });

  console.log(`${createdModels.count} model(s) created`);
}
